"""empty message

Revision ID: dcc8bb27d13b
Revises: 
Create Date: 2021-07-12 13:52:23.483889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcc8bb27d13b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alembic_version")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version_num"),
    )
    # ### end Alembic commands ###
