"""empty message

Revision ID: 7ee0965fde24
Revises: fce172b317cf
Create Date: 2021-07-09 05:04:35.392968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ee0965fde24"
down_revision = "fce172b317cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribed_days",
        sa.Column("large_future_formula", sa.NUMERIC(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribed_days", "large_future_formula")
    # ### end Alembic commands ###
