"""empty message

Revision ID: 0b498d934dd2
Revises: 7ee0965fde24
Create Date: 2021-07-09 05:16:53.359996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b498d934dd2"
down_revision = "7ee0965fde24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribed_days", "large_future_formula")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribed_days",
        sa.Column(
            "large_future_formula",
            sa.DECIMAL(precision=38, scale=0),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
