"""empty message

Revision ID: 6c55ccfd8e32
Revises: ce5f7d01cb00
Create Date: 2021-07-12 22:44:16.373311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c55ccfd8e32"
down_revision = "ce5f7d01cb00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "retention", sa.Column("retention_rate", sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("retention", "retention_rate")
    # ### end Alembic commands ###
