"""empty message

Revision ID: ce5f7d01cb00
Revises: b5f45d03ece3
Create Date: 2021-07-12 22:26:26.219674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce5f7d01cb00"
down_revision = "b5f45d03ece3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("retention", "retention_rate")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "retention",
        sa.Column(
            "retention_rate", sa.FLOAT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
