"""empty message

Revision ID: f121194c73e0
Revises: 0b498d934dd2
Create Date: 2021-07-09 17:19:39.318236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f121194c73e0"
down_revision = "0b498d934dd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribed_days",
        sa.Column("large_future_formula", sa.NUMERIC(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribed_days", "large_future_formula")
    # ### end Alembic commands ###
