"""empty message

Revision ID: d3d6aa84f203
Revises: ec07edab28e7
Create Date: 2021-07-12 22:44:22.976424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3d6aa84f203"
down_revision = "ec07edab28e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_ltv", sa.Column("predicted_gp", sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_ltv", "predicted_gp")
    # ### end Alembic commands ###
