"""empty message

Revision ID: ec07edab28e7
Revises: 829e0be18f77
Create Date: 2021-07-12 22:26:30.926116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec07edab28e7"
down_revision = "829e0be18f77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_ltv", "predicted_gp")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_ltv",
        sa.Column(
            "predicted_gp", sa.FLOAT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
