name: snowflake schema change

on:
  pull_request:
    branches:
      - main
    paths:
      - snowflake_migrations/models/**

env:
  SNOWFLAKE_URL: ${{ secrets.SNOWFLAKE_DB }}
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependency
        run: python3 -m pip install -r requirements.txt
      - name: run alembic
        working-directory: ./snowflake_migrations
#        run: alembic --name data_definitions revision --autogenerate
        run: echo $(PWD)
