name: snowflake schema change

on:
  pull_request:
    branches:
      - main
    paths:
      - snowflake_migrations/models/**
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: print
        run: echo  ${{ github.ref }}

      - name: print
        run: echo "Done"

